name: Auto Clean VPN List

on:
  schedule:
    - cron: '0 * * * *'  # Запуск автоматически каждый час
  workflow_dispatch:     # Кнопка для ручного запуска

jobs:
  run-cleaner:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование вашего репозитория
      uses: actions/checkout@v4

    # Скачиваем файл через официальное внутреннее API GitHub и сразу чистим от комментов (#)
    - name: Скачивание и очистка списка подписки
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh api repos/igareck/vpn-configs-for-russia/contents/BLACK_SS+All_RUS.txt -q '.content' | base64 -d > downloaded.txt
        
        # Убираем все закомментированные '#' и пустые строки
        grep -v '^[[:space:]]*#' downloaded.txt | grep -v '^[[:space:]]*$' > cleaned_subscription.txt

    - name: Запись очищенного файла обратно в ваш репозиторий
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        git add cleaned_subscription.txt
        git commit -m "Автоматическое обновление подписки (удалены комментарии)" || exit 0
        git push
